/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo4proyecto;

//Paquetes
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Juan Jose
 */
public class framePrograma extends javax.swing.JFrame {
    //Declaramos los atributos para definir el panel Y para instanciar las interfaces
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private InterfazInicial interfazInicial;
    private Interfaz interfaz;
    
    public framePrograma() {
        initCustomComponents();
    }
    private void initCustomComponents() {
        setTitle("Programa de Reservas Empresarial");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);

        //UI personalizada 
        UIManager.put("Button.font", new Font("Arial", Font.PLAIN, 14));
        UIManager.put("Label.font", new Font("Arial", Font.PLAIN, 14));
        UIManager.put("Panel.background", Color.WHITE);
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        //Instancia la interfaz inicial y pasa parametros para que el panel sea visible
        interfazInicial = new InterfazInicial(true, 0, this);
        interfaz = new Interfaz("Juan Jose", "12345", this); //Datos predeterminados para testear

        //Añadir las dos interfaces al mismo panel
        mainPanel.add(interfazInicial.getPanel(), "InterfazInicial");
        mainPanel.add(interfaz.getPanel(), "Interfaz");
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        cardLayout.show(mainPanel, "InterfazInicial");
    }
    public void showPanel(String panelName) {
        cardLayout.show(mainPanel, panelName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            framePrograma frame = new framePrograma();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
