/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo4proyecto;

//Paquetes
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Juan Jose
 */
public class framePrograma extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel mainPanel;
    private InterfazInicial interfazInicial;
    private Interfaz interfaz;
    
    public framePrograma() {
        initCustomComponents();
    }
    private void initCustomComponents() {
        setTitle("Programa de Reservas Empresarial");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);

        // Estilo empresarial
        UIManager.put("Button.font", new Font("Arial", Font.PLAIN, 14));
        UIManager.put("Label.font", new Font("Arial", Font.PLAIN, 14));
        UIManager.put("Panel.background", Color.WHITE);

        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // Inicializar las interfaces
        interfazInicial = new InterfazInicial(true, 0, this);
        interfaz = new Interfaz("Juan Jose", "12345", this);

        // Añadir las interfaces al panel principal
        mainPanel.add(interfazInicial.getPanel(), "InterfazInicial");
        mainPanel.add(interfaz.getPanel(), "Interfaz");

        // Añadir el panel principal al frame
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        cardLayout.show(mainPanel, "InterfazInicial");
    }
    public void showPanel(String panelName) {
        cardLayout.show(mainPanel, panelName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            framePrograma frame = new framePrograma();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
